spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: postgres
    password: manohar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
